---
apiVersion: v1
kind: Namespace
metadata:
  name: lightbend

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
  namespace: lightbend
data:
  alertmanager.yml: |-
    global:
      # ref:  https://typesafe.slack.com/apps/new/incoming-webhooks
      slack_api_url: 'https://hooks.slack.com/services/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'

    receivers:
      - name: slack-test
        slack_configs:
        - channel: '#test-es-alert'
          send_resolved: true

    route:
      receiver: slack-test
      group_by: [workload]

    # don't alert on warnings if the same alert is already critical
    inhibit_rules:
    - source_match:
        severity: critical
      target_match:
        severity: warning
      equal: [alertname]

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: prometheus-alertmanager
  namespace: lightbend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
  template:
    metadata:
      labels:
        app: prometheus
        component: alertmanager
    spec:
      serviceAccountName: default
      containers:
        - name: prometheus-alertmanager
          image: prom/alertmanager:v0.14.0
          imagePullPolicy: IfNotPresent
          env:
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data

          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

        - name: prometheus-alertmanager-configmap-reload
          image: jimmidyson/configmap-reload:v0.1
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: expose-alertmanager
  namespace: lightbend
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 30093
  selector:
    app: prometheus
    component: alertmanager
  type: NodePort
